Repository the-bone-yard/backend-repo, pull requests merged in 2021-01, with the labels that each got.

#9 Create basic landing page
  boneyardproj/urls.py
  main_app/views.py
  templates/main_app/index.html
Labels: backend, setup

#12 API call made and reformatted (serialized)
  boneyardproj/urls.py
  main_app/services.py
Labels: api, backend

#13 Creats new tests directory and test file for a generic API call
  main_app/tests/test_app.py
Labels: api, backend, testing

#17 Creates a working API
  boneyardproj/urls.py
  main_app/services.py
  main_app/views.py
Labels: api, backend

#19 Sets up properly consuming Google Places API
  boneyardproj/urls.py
  main_app/services.py
Labels: api, backend, enhancement

#21 Adds HTML styling to the lading page
  templates/main_app/index.html
Labels: styling

#22 Testing .gitignore file and API changes
  .gitignore
  boneyardproj/settings.py
  main_app/models.py
  main_app/services.py
  main_app/tests/test_app.py
Labels: api, backend, bug

#23 Bug fix for environmental variables
  .gitignore
  boneyardproj/settings.py
  main_app/models.py
  main_app/services.py
Labels: api, bug

#24 Heroku app crash
  .gitignore
  boneyardproj/settings.py
  boneyardproj/urls.py
  requirements.txt
Labels: api, bug

#25 Had issues with Heroku app crashing, fixed bug
  boneyardproj/settings.py
  main_app/services.py
Labels: api, bug, refactor

#26 Testing Heroku auto-deployment
  main_app/services.py
Labels: backend, bug

#27 Installs new library for FE to access endpoint
  boneyardproj/settings.py
  main_app/services.py
  main_app/tests/test_app.py
  requirements.txt
Labels: api, backend, bug, frontend, setup

#28 Increases radius of search results from 2000m to 48000m
  main_app/services.py
Labels: api, backend, frontend

#31 Creates feature of searching parks near location different from current (and tests)
  boneyardproj/urls.py
  main_app/services.py
  main_app/tests/test_app.py
Labels: api, backend, enhancement

#32 Refactor 'services.py'
  boneyardproj/urls.py
  main_app/serializer.py
  main_app/services.py
Labels: backend, refactor

#34 Passes User creation test
  boneyardproj/settings.py
  boneyardproj/urls.py
  main_app/migrations/0001_initial.py
  main_app/migrations/0002_park.py
  main_app/migrations/0003_auto_20210112_2334.py
  main_app/migrations/0004_park_photo.py
  main_app/migrations/0005_park_rating.py
  main_app/models.py
  main_app/tests/test_models.py
  park/__init__.py
  park/apps.py
  park/serializers.py
  park/tests/_init_.py
  park/tests/test_park_api.py
  park/urls.py
  park/views.py
Labels: api, backend, testing

#35 Fixes Heroku app crashing
  main_app/models.py
  main_app/services.py
  main_app/tests/test_app.py
  main_app/tests/test_models.py
  park/urls.py
  park/views.py
  requirements.txt
Labels: backend, bug

#36 Made several changes to settings and requirements file
  boneyardproj/settings.py
  requirements.txt
Labels: backend, bug

#37 Adds email, lat and lng to park model
  main_app/migrations/0006_auto_20210113_1531.py
  main_app/models.py
  main_app/tests/test_app.py
  main_app/tests/test_models.py
Labels: backend, enhancement

#39 Directions endpoint with accompanying test
  main_app/serializer.py
  main_app/services.py
  main_app/tests/test_app.py
Labels: api, enhancement

#40 Adds formatting for get all parks
  main_app/models.py
  main_app/services.py
Labels: api, backend, refactor

#41 Reformat parks object that comes back in Park.all
  main_app/services.py
Labels: api, backend, bug
